webapp:
  build: .
  dockerfile: Dockerfile.webapp
  ports:
   - "localhost:8088:8080"
  environment:
   - PSQL_USER=interminer
   - PSQL_PWD=interminer0312
   - TOMCAT_USER=tomcat
   - TOMCAT_PWD=tomcat0312
   - TOMCAT_PORT=8080
   - PSQL_DB_NAME=malariamine
   - DB_NAME=malariamine
  volumes_from:
   - data
  links:
   - postgres
data:
  image: centos:centos7
  volumes:
    - ./malariamine:/data
  entrypoint: ["tail", "-f", "/dev/null"]
postgres:
  image: postgres
